export const POST_PROVIDER = "POST_PROVIDER";
export const GET_EXCHANGE_RATES = "GET_EXCHANGE_RATES ";
export const GET_EXCHANGE_RATES_PER_YEAR = "GET_EXCHANGE_RATES_PER_YEAR ";
export const PROVIDER_ERROR = "PROVIDER_ERROR";
export const GET_EXCHANGE_RATES_ERROR = "GET_EXCHANGE_RATES_ERROR ";
export const GET_EXCHANGE_RATES_PER_YEAR_ERROR = "GET_EXCHANGE_RATES_PER_YEAR_ERROR ";
